name: Build NekoMenu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: Build DLL
      run: dotnet build NekoMenu.csproj -c Release
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NekoMenu-DLL
        path: bin/Release/**/*.dll
